# Generated by Django 4.2.1 on 2023-06-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_location_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location",
            new_name="locations",
        ),
    ]
