# Generated by Django 4.2.1 on 2023-06-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_locations_user_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ManyToManyField(to="users.location"),
        ),
    ]
