# Generated by Django 4.2.1 on 2023-06-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options_remove_user_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location",
            new_name="locations",
        ),
    ]
