# Generated by Django 4.2.2 on 2023-06-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
