# Generated by Django 4.2.1 on 2023-06-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_rename_categorie_category_alter_ad_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
