# Generated by Django 4.2.1 on 2023-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_alter_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
